import 'package:flutter/material.dart';

TextStyle heading1 = const TextStyle(fontFamily: "DMSans", fontSize: 26.0, fontWeight: FontWeight.w600);
TextStyle heading2 = const TextStyle(fontFamily: "DMSans", fontSize: 22.0, fontWeight: FontWeight.w600);
TextStyle heading3 = const TextStyle(fontFamily: "Mulish", fontSize: 22.0, fontWeight: FontWeight.w700);
TextStyle heading4 = const TextStyle(fontFamily: "Mulish", fontSize: 18.0, fontWeight: FontWeight.w600);
TextStyle heading5 = const TextStyle(fontFamily: "Mulish", fontSize: 16.0, fontWeight: FontWeight.w600);
TextStyle subtitle1 = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w600);
TextStyle body1 = const TextStyle(fontFamily: "Mulish", fontSize: 16.0, fontWeight: FontWeight.w500);
TextStyle body2 = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w500);
TextStyle caption1 = const TextStyle(fontFamily: "Mulish", fontSize: 15.0, fontWeight: FontWeight.w400);
TextStyle caption2 = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w500);
TextStyle caption3 = const TextStyle(fontFamily: "Mulish", fontSize: 12.0, fontWeight: FontWeight.w400);
TextStyle smallbutton = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w600);
TextStyle mediumbutton = const TextStyle(fontFamily: "Mulish", fontSize: 16.0, fontWeight: FontWeight.w600);
TextStyle extrabutton = const TextStyle(fontFamily: "Mulish", fontSize: 16.0, fontWeight: FontWeight.w800);
TextStyle pricesmall = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w700);
TextStyle pricemedium = const TextStyle(fontFamily: "Mulish", fontSize: 16.0, fontWeight: FontWeight.w800);
TextStyle pricelarge = const TextStyle(fontFamily: "Mulish", fontSize: 24.0, fontWeight: FontWeight.w700);
TextStyle cardsmall = const TextStyle(fontFamily: "Mulish", fontSize: 12.0, fontWeight: FontWeight.w600);
TextStyle cardlarge = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w600);
TextStyle inputlabelinternal = const TextStyle(fontFamily: "Mulish", fontSize: 12.0, fontWeight: FontWeight.w400);
TextStyle inputlabeldefault = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w400);
TextStyle inputlabelexternal = const TextStyle(fontFamily: "Mulish", fontSize: 13.0, fontWeight: FontWeight.w600);
TextStyle inputlabelplaceholder = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w600);
TextStyle inputlabelplaceholderactive = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w500);
TextStyle inputlabelplaceholderdefault = const TextStyle(fontFamily: "Mulish", fontSize: 14.0, fontWeight: FontWeight.w600);
