import 'package:secret_spice/core/db/models/recipe_model.dart';

const List<RecipeModel> recipes = [
  RecipeModel(
    id: 1,
    name:
        "Achari Amla Mirchi Ki Sabzi Recipe - Gooseberry & Green Chilli Sabzi",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Amla_Mirchi_Ka_Achari_Subzi_Recipe_Gooseberry__Green_Chilli_Subzi.jpg",
    description:
        "Achari Amla Mirchi Ki Sabzi Recipe also called as Gooseberry & Green Chilli Sabzi, a dry curry that has the right amount of sourness and spiciness in the dish. Amla is a powerhouse of Vitamin C and is great for hair and skin. It is also rich in antioxidants and fiber, thus it is also diabetic friendly dish. Therefore adding amla into your everyday diet will help you in a lot of ways.",
    diet: Diet.veg,
    ingredients: [
      "Amla",
      "Green Chille",
      "Achari Masala",
      "Chilli Powder",
      "Turmeric Powder",
      "Jaggery",
      "Salt",
      "Fennel Seeds",
      "Methi Seeds",
      "Mustard Seeds",
      "Oil",
      "Asafoetida",
    ],
    preparations: [
      "To begin making the Achari Amla Mirchi Ki Sabzi Recipe, heat a pressure cooker with oil, add amla and green chilli along with all the masala including achari masala, red chilli powder, turmeric powder, salt except the jaggery.",
      "Add about 1/4 cup of water and pressure cook for 2 whistle and switch it off.",
      "Allow the pressure to release naturally. Open the lid and keep the pressure cooker back on the stove.",
      "Add jaggery and keep cooking until Amla Mirchi Ki Sabzi dries up. Once done turn off the heat.",
      "Keep it aside, heat a tadka pan with oil, add fennel seeds, fenugreek seeds and mustard seeds allow them to crackle.",
      "Add pinch of hing and then pour it over the sabzi, give Achari Amla Mirchi Ki Sabzia mix and serve hot.",
      "Serve the Achari Amla Mirchi Ki Sabzi Recipe along with Roti and Traditional Punjabi Kadhi With Methi for a weekday meal.",
    ],
    nutritions: Nutritions(
      calories: 44,
      carbs: 10.2,
      fats: 0.58,
      protiens: 6.5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 2,
    name: "Andhra Style Vegetarian Biryani with Soya Chunks Recipe",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Andhra_Style_Vegetarian_Biryani_with_Soya_Chunks_Recipe_is_.jpg",
    description:
        "Andhra Style Vegetarian Biryani with Soya Chunks Recipe is very different from the Hyderabadi Biryani. The rice is completely tossed with the spicy masala rather than layering the rice with Biryani masala. The chopped tomatoes and ground spice mix will adds in the extra flavor to the rice. Andhra recipes are quite spicy when compared to dishes from other states. The flavors also change from region to region.",
    diet: Diet.veg,
    ingredients: [
      "Basmati Rice",
      "Soy Chunks",
      "Onions",
      "Tomatoes",
      "Green Chilli",
      "Ginger Garlic Paste",
      "Turmeric powder",
      "Oil",
      "Bay Leaf",
      "Cardamom",
      "Cloves",
      "Cinnamon Stick",
      "Anise",
    ],
    preparations: [
      "To begin making the Andhra Style Vegetarian Biryani, soak the soy chunks in 1/4 cup water and keep it aside.",
      "Soak the basmati rice also in water and keep it aside. Ground all the spice mix mentioned in the biryani spice mix to a coarse powder.",
      "Heat a pressure cooker with oil. Add bay leaf, cardamom, cinnamon stick, cloves, star anise and mace.",
      "Fry the spice for 10 seconds until the aroma is released.",
      "Add the chopped onions, ginger garlic paste and green chili.",
      "Saut until the onions become light brown. Add the chopped tomatoes and little bit of salt so that the tomatoes will get cooked faster and become mushy.",
      "Add the powdered spice mix, turmeric powder and give it a mix. Wash the soaked rice several times and add only the rice into the sauted gravy.",
      "Add the soaked soya chunks as well. Mix well till the masala is mixed.",
      "Add 4 cups of water, check for salt and pressure cook for 2 whistle and switch off the heat.",
      "Allow the pressure to release by itself and open the lid and mix the rice well with the masala and serve.",
      "Serve the Andhra Style Vegetarian Biryani with Tomato Onion Cucumber Raita and Mirchi Ka Salan Recipe by the side.",
    ],
    nutritions: Nutritions(
      calories: 120,
      carbs: 22.5,
      fats: 3,
      protiens: 6.5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 3,
    name: "Bhaat Na Rasawala Muthia Dhokla Recipe Gujarati Rasiya Dhokla",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Andhra_Style_Vegetarian_Biryani_with_Soya_Chunks_Recipe_is_.jpg",
    description:
        "If you love Kadhi Chawal, then you will absolutely love this one dish meal bowl which is a classic and traditional kathiyawadi dish called Bhaat Na Rasawala Muthia Dhokla made from rice dumplings simmered in a delicious kadhi. Serve the Bhaat Na Rasawala Muthia Dhokla as a one dish meal for any weeknight dinner when you are looking for a comforting meal.",
    diet: Diet.veg,
    ingredients: [
      "Cooked Rice",
      "Gram Flour",
      "Red Chilli powder",
      "Turmeric powder",
      "Salt",
      "Curd",
      "Green Chilli",
      "Ginger",
      "Bay Leaf",
      "Oil",
      "Cinnamon Stick",
      "Cumin Seeds",
      "Curry Leaves",
    ],
    preparations: [
      "To make Bhaat Na Rasawala Muthia Dhokla, prep all the ingredients and keep them ready.",
      "Into a large mixing bowl, combine all the muthia dhokla ingredients and mash the rice well until it forms a dough like consistency.",
      "Grease your palms, shape into small ovals (muthias) and keep aside.",
      "For kadhi, into a sauce pan combine the dahi, besan, turmeric powder, salt and red chilli powder and mix well to combine until there are no lumps.",
      "Add the 3 cups of water and bring to a brisk boil.",
      "Keep whisking the Kadhi as it continues to boil, as this makes it smooth and creamy, thus giving it a perfect texture.",
      "Once the kadhi has come together into a smooth and creamy mixture while it is boiling, turn the heat to low, add the ginger garlic, green chillies, cinnamon stick and simmer kadhi while we add the muthias.",
      "Add the muthia into the kadhi. Simmer for at least 5 minutes and you will notice the muthia‘s rising to the top and floating.",
      "Once it begins to float to the top, simmer the Bhaat Na Rasawala Muthia Dhokla for another 2 minutes.",
      "The final step is to prepare the tadka. Heat ghee in a saucepan on medium heat; add the cumin seeds and allow them to crackle. Stir in the curry leaves, cinnamon and give it a stir.",
      "Gradually, add the seasoning mixture to the above Rasiya Dhokla/Bhaat Na Rasawala Muthia Dhokla and allow the mixture to come to a brisk boil and turn off the heat.",
      "Serve the Bhaat Na Rasawala Muthia Dhokla as a one dish meal for any weeknight dinner when you are looking for a comforting meal.",
    ],
    nutritions: Nutritions(
      calories: 180,
      carbs: 27,
      fats: 4,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 4,
    name: "Bhindi And Paneer Masala Recipe",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Bhindi_and_Paneer_Masala_Gravy_Recipe_.jpg",
    description:
        "Bhindi and Paneer Masala Recipe is a simple side dish which is made with sauted bhindi and soft paneer in a tomato based gravy without any addition of cashew nuts, poppy seeds or cream. The flavors are simple and the whole spices are ground along with tomato so that it is more flavourful.",
    diet: Diet.veg,
    ingredients: [
      "Lady Finger",
      "Paneer",
      "Onion",
      "Bay Leaf",
      "Red Chilli Powder",
      "Turmeric Powder",
      "Corainder Powder",
      "Sugar",
      "Salt",
      "Oil",
      "Tomatoes",
      "Cloves",
      "Cinnamon Stick",
      "Cardamom",
      "Garlic",
      "Ginger",
      "Hung Curd",
    ],
    preparations: [
      "To begin making the Bhindi and Paneer Masala Recipe, grind the tomatoes along with cinnamon, cardamom, clove, garlic, ginger and yogurt to a smooth paste.",
      "Heat a kadai with oil, add the chopped ladies finger and fry them till it is soft and crispy. Sprinkle little salt also and fry them. Keep it aside.",
      "In the same kadai, add little more oil, add bay leaf, chopped onions and saute till it becomes translucent.",
      "Add the ground paste along with turmeric powder, red chilli powder, coriander powder, sugar and salt. Mix well and saute till the raw smell of the tomato goes away.",
      "Add the chopped ladies finger and paneer and mix well. Check for salt and cover it with a lid and cook Bhindi and Paneer Masala for 2 minutes. Serve hot.",
      "Serve the Bhindi and Paneer Masala Recipe along with Tawa Paratha, Palak Dal and Lauki Raita to make your dinner meals simple and healthy.",
    ],
    nutritions: Nutritions(
      calories: 150,
      carbs: 15,
      fats: 10,
      protiens: 8,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 5,
    name: "Carrots & Sweet Potato Stuffed Paratha Recipe",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sibyl_sunitha/Carrot__Sweet_Potato_Paratha_Recipe.jpg",
    description:
        "Carrots and Sweet Potato Stuffed Parathas are a whole wheat Indian flat bread stuffed with finely grated carrots and boiled sweet potatoes are spiced up with green chillies, coriander leaves and cumin powder, makes this paratha healthy and delicious. This is a favorite lunch box for my children, they love to have it along with honey. And not to miss it is wholesome and nutritious too.",
    diet: Diet.veg,
    ingredients: [
      "Wheat Flour",
      "Salt",
      "Oil",
      "Carrots",
      "Sweet Potatoes",
      "Cumin powder",
      "Green Chillies",
      "Corainder",
    ],
    preparations: [
      "To begin making the sweet potato parathas, we will first make the dough. Add flour and salt in a large bowl, adding little water at a time to make soft, pliable dough.Knead dough until it is smooth and elastic. Add oil to coat the dough and knead little more. The dough will be soft and nonsticky. Allow the dough to rest for about 15 minutes, covered.",
      "Knead dough until it is smooth and elastic. Add oil to coat the dough and knead little more. The dough will be soft and nonsticky. Allow the dough to rest for about 15 minutes, covered.",
      "Divide the dough into lemon sized balls and roll them out thin to approximately 3 inches in diameter. Note tossing the dough in dry flour while rolling will prevent it from getting sticky when rolling them out.",
      "In another bowl, combine all the ingredients for the filling together. Check the salt and spices and adjust to suit your taste.",
      "Add 1 tablespoon of the stuffing in the center. Gather the sides and bring them together. Remove the little excess dough which popped out when you brought them together.",
      "Press the stuffed dough down. Toss it in some flour and roll it gently applying just even pressure to roll. Roll it to desired thickness and your comfort level in rolling.",
      "Place the stuffed sweet potato carrot parathas on the hot griddle/skillet. Cook on medium heat adding a little oil or ghee to cook the parathas until you notice it gets brown spots on both the sides and has lightly crisp outer crust.",
      "Serve Carrots & Sweet Potato Stuffed Paratha Recipe along with Boondi Raita Recipe Spiced With Black Salt, Instant Gor Kairi Lonche Recipe - Sweet Raw Mango Pickle and Apple, Kiwi, Pineapple Juice Recipe for a complete breakfast.",
    ],
    nutritions: Nutritions(
      calories: 220,
      carbs: 35,
      fats: 8,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 6,
    name: "Chettinad Style Kara Kuzhambu Recipe with Potato and Brinjal",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/mkavya87-gmail.com/Chettinad_Style_Kara_Kuzhambu_Recipe_with_Potato_and_Brinjal_1_1600.jpg",
    description:
        "Chettinad Style Kara Kuzhambu Recipe with Potato and Brinjal is a finger licking good recipe made the Chettinad way. The pearl onions in the kuzhambu along with the freshly ground spice masala and samabr powder give it the rich taste. Adding potatoes and brinjal, add nutrition and completely elevate the kara kuzhambu. Serve Chettinad Style Kara Kuzhambu Recipe with Potato and Brinjal along with Steamed Rice, Beetroot Thoran and Elai Vadam for a weekday meal.",
    diet: Diet.veg,
    ingredients: [
      "Methi Seeds",
      "Coriander",
      "Fennel seeds",
      "Dry Red Chillies",
      "Coconut",
      "Pearl Onions",
      "Garlic",
      "Tomatoes",
      "Potatoes",
      "Brinjal",
      "Jaggery",
      "Oil",
      "Mustard Seeds",
      "Curry Leaves",
      "Tamarind Water",
      "Sambar Powder",
    ],
    preparations: [
      "To begin making the Chettinad Style Kara Kuzhambu Recipe, we will first make the masala.",
      "Heat a small pan on medium heat; add fenugreek seeds, coriander seeds, fennel seeds, red chillies. Roast these spices until the aroma wafts in the air. Stir in the freshly grated coconut and roast for another 2 to 3 minutes.",
      "Turn off the heat and allow the spices to cool. Transfer the spices into a mixer jar, add 1/2 cup warm water and grind to make a smooth paste.",
      "To cook the kara kuzhambu, heat oil in a pressure cooker over medium heat; add the onion, garlic and saute for a few minutes until the onion softens. Add the chopped tomatoes and saute until the tomatoes are mushy.",
      "Stir in the potatoes, brinjal, jaggery, tamarind water, sambar powder and salt. Pressure cook for 3 to whistles and turn off the heat and allow the pressure to release naturally.",
      "In the meantime, make the seasoning; heat oil in a tadka pan; add the mustard seeds and curry leaves and allow it to crackle. Turn off the heat and keep aside.",
      "Once the pressure releases, stir in the coconut mixture, the seasoning mixture and give the Chetinnad Kara Kuzhambu a brisk boil for 3 to 4 minutes. Check the salt and adjust according to taste.",
      "Serve hot Chettinadu Style Potato Kaarakozhambu along with Steamed Rice, Beetroot Thoran and Elai Vadam for a weekday meal.",
    ],
    nutritions: Nutritions(
      calories: 70,
      carbs: 12,
      fats: 4,
      protiens: 4,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 7,
    name: "Goan Chana Ros Recipe (White Peas Curry)",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Raksha_Kamat/Goan_Chana_Ross.jpg",
    description:
        "Goan Chana Ros is a vegetarian dish from Goan cuisine made with dried white peas (safed vatana). In Ros recipes, we add freshly grated coconut, instead of roasted coconut which is used for many other Goan dishes. Simply roast the spices and grind along with freshly grated coconut and add to the boiled white peas to prepare this recipe. Serve Goan Chana Ros recipe with steamed rice, Kelyachyo Fodi (banana) to have a nice Goan vegetarian meal. You can also serve chana Ros with bread and rotis, but we prefer to have it as a side dish with rice.",
    diet: Diet.veg,
    ingredients: [
      "Green Peas",
      "Onion",
      "Coconut",
      "Dry Red Chillies",
      "Coriander seeds",
      "Cloves",
      "Tamarind",
      "Turmeric Powder",
      "Salt",
    ],
    preparations: [
      "To prepare Goan Chana Ros recipe, soak the white peas in water for 8 hours or overnight.",
      "Pressure cook the white peas along with chopped onions by adding 1 cup water for 4-5 whistles or till boiled. Let the pressure from pressure cooker get released on its own.",
      "Dry roast coriander seeds, dry red chilies and cloves together, till nice aroma gets emitted from coriander seeds. Let it cool down.",
      "Take a Mixer and add grated coconut, tamarind and dry roasted spices. Add 1/2 to 3/4 cup water and grind this into a smooth paste.",
      "Now take a Kadai and add the ground gravy to it. Switch on the gas and keep it on low flame.",
      "After 5 minutes, add the boiled white peas along with onion to the gravy and mix well. If the gravy is thick, add remaining water from the pressure cooker and mix.",
      "Add salt to taste and simmer for 10 minutes before switching off the gas.",
      "Serve Goan Chana Ros recipe with hot rice, Kelyachyo Fodi (banana)",
    ],
    nutritions: Nutritions(
      calories: 100,
      carbs: 15,
      fats: 3,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 8,
    name: "Goan Style Mushroom Vindaloo Recipe",
    image_url:
        "https://www.archanaskitchen.com/images/archanaskitchen/0-Archanas-Kitchen-Recipes/2016/sept-26/Goan_Style_Mushroom_Vindaloo_Recipe-1.jpg",
    description:
        "Goan Style Mushroom Vindaloo Recipe is a variation of the classic Goan Pork Vindaloo recipe. This traditional dish was introduced by the Portuguese in Goa. In this recipe, the mushroom is cooked in a vinegar based curry infused with Indian spices.",
    diet: Diet.veg,
    ingredients: [
      "Button Mushrooms",
      "Onion",
      "Garlic",
      "Ginger",
      "Turmeric Powder",
      "Oil",
      "Salt",
      "Red Chillies",
      "Corainder",
      "Cumin Seeds",
      "Black Peppercorns",
      "Cloves",
    ],
    preparations: [
      "To begin making the Goan Style Mushroom Vindaloo, first prep all the ingredients, and get all the spices together.",
      "The next step is to roast the masala for the vindaloo. Heat a small skillet over medium heat add all the ingredients to be ground into a paste and roast them for a few minutes until you get a roasted aroma and the red chilies are lightly crisp.",
      "Turn off the heat, allow it to cool a bit and grind into a fine powder. Pound the ginger and garlic in a pestle and motor and keep aside.",
      "Heat oil in a pan add the ginger garlic paste and saute for a few seconds. Add the chopped onions and saute until the onions are tender.",
      "Add the turmeric powder, the ground spice powder, the mushrooms. Add the salt, cover the pan and simmer for 10 minutes until the mushrooms are cooked.",
      "Once done, open the pan, and allow the vindaloo masala to thicken, but evaporating any excess liquid. Turn off the heat and serve warm. Serve the Goan Style Mushroom Vindaloo along with steamed rice or even lachha paratha for lunch.",
    ],
    nutritions: Nutritions(
      calories: 80,
      carbs: 12,
      fats: 3,
      protiens: 3,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 9,
    name: "Kongunadu Style Vetrilai Sadam Recipe - Betel Leaves Rice",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/swathynandhini/Vethalai_Sadam_1600.jpg",
    description: "Vetrilai Sadam or Betel Leaves Sadam is a traditional Kongunadu special variety of rice. It is healthy, flavorful, and tasty that gets a peppery flavor from the betel nut leaves. Preparing this rice requires grounded masala that adds flavor to it. Betel leaves have many health benefits, it is rich in calcium and aids in digestion. This rice has unique flavors of betel leaves and garlic.",
    diet: Diet.veg,
    ingredients: [
      "Betel Leaves",
      "Cooked Rice",
      "Garlic",
      "Oil",
      "Mustard Seeds",
      "Chana Dal",
      "Urad Dal",
      "Curry Leaves",
      "Roasted Peanuts",
      "Cashew Nuts",
      "Red Chillies",
      "Salt",
      "Cumin Seeds",
    ],
    preparations: [
      "To begin making Kongunadu Style Vetrilai Sadam Recipe, wash and cook rice adding just sufficient water so that the rice is not sticky and the grains are cooked yet separate. You can also use leftover rice for preparing this.",
      "Next, we will prepare the masala for the rice. Dry roast Cumin seeds, Fennel seeds, Pepper seeds, and Sesame seeds until golden. Add the curry leaves and roast for another minute. Allow it to cool completely and grind into a coarse powder.",
      "Heat a Kadai with oil, add mustard seeds, chana dal, and Urad dal. Once the dals turn golden brown add curry leaves, chopped red chillies, peanuts, and cashews. Saute until the cashews and peanuts turn a golden color.",
      "Add crushed garlic and saute until the raw smell goes away. Tear the betel leaves roughly and add them to the pan and saute until the leaves shrink.",
      "Now add the ground masala powder and stir all ingredients well for a minute. Turn off the heat and add cooked rice along with the required salt.",
      "Toss and mix well until everything is combined. Check for salt and serve Kongunadu Style Vetrilai Sadam hot.",
      "Serve Vetrilai Sadam or Betel Leaves Sadam along with Tomato Cucumber Raita and Masala Vadai for a wonderful Sunday lunch.",
    ],
    nutritions: Nutritions(
      calories: 200,
      carbs: 40,
      fats: 4,
      protiens: 4,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 10,
    name: "Sindhi Style Wadi Aloo Ki Sabzi Recipe - Spicy Wadi And Potato Curry",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/varshajchhabria-gmail.com/Sindhi_Style_WAdi_Aloo_ki_sabzi__1600.jpg",
    description: "Sindhi Style Wadi Aloo Ki Sabzi is an authentic Sindhi dish which is made with sundried dal spiced dumplings called Wadis, that are cooked along with potatoes and brinjals in an onion tomato gravy.",
    diet: Diet.veg,
    ingredients: [
      "Oil",
      "Urad Dal",
      "Onion",
      "Tomatoes",
      "Ginger",
      "Potato",
      "Brinjal",
      "Red Chilly Powder",
      "Cumin Powder",
      "Garam Masala",
      "Coriander Powder",
    ],
    preparations: [
      "To begin making the Sindhi Style Wadi Aloo Ki Sabzi Recipe, in a pressure cooker heat oil on medium flame. Add chopped onions and saute for 3-4 minutes, until it turns into golden brown in colour. To this add wadi/urad dal dumpling and saut for 3-4 minutes or until the wadi turns red.",
      "Close the pressure cooker and cook for 3 whistles.",
      "Turn off the heat and let the pressure release naturally. Once the pressure has released, remove only the wadis and place it in a bowl.",
      "Combine tomatoes and ginger in a mixer jar and bring to a pure, transfer to a bowl and set aside.",
      "Heat the same pressure cooker with the onions on medium heat, add the potato and brinjal wedges and continue to cook for another 5 minutes.",
      "At this stage add, red chilli powder, garam masala powder, cumin powder, coriander powder and salt. Give it a good stir.",
      "Now that the onions, potatoes and brinjal are well coated with the masala, add the tomato ginger pure, saut for 3 minutes.",
      "Add the pre cooked wadi and close the pressure cooker.",
      "Pressure cook for 3 whistles, reduce the heat and continue to cook for 5 more minutes.",
      "Turn off the heat and allow the pressure to release naturally.",
      "Serve Sindhi Style Wadi Aloo Ki Sabzi Recipe along with Phulka and Palak Raita for your everyday vegetarian Lunch or Dinner.",
    ],
    nutritions: Nutritions(
      calories: 170,
      carbs: 20,
      fats: 10,
      protiens: 6,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 11,
    name: "Spicy Cabbage Rice Recipe (South Indian Style Mutta Kose Sadham Recipe)",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Pooja_Thakur/Spicy_Cabbage_Rice.jpg",
    description: "Spicy Cabbage Rice takes very few ingredients to make and takes hardly 20 minutes to get prepared. This is a perfect recipe if you want to use your leftover rice and can be packed in your lunch box too. Serve Spicy Cabbage Rice Recipe with raita of your choice.",
    diet: Diet.veg,
    ingredients: [
      "Cooked Rice",
      "Oil",
      "Cumin Seeds",
      "Onion",
      "Cabbage",
      "Green Chillies",
      "Red Chilly Powder",
      "Turmeric Powder",
      "Sambar Powder",
      "Coriander Leaves",
    ],
    preparations: [
      "To prepare Spicy Cabbage Rice recipe, firstly heat oil in a kadai. Add cumin seeds, green chillies and let it cook for 15 seconds.",
      "Next, add in the sliced onions and cook till they become soft and translucent. Add in the shredded cabbage, salt and turmeric powder. Cook till the cabbage becomes soft. Once it is done, add in the cooked rice, red chilli powder and the sambar powder.",
      "Mix everything well.Cover for 2 minutes. Open the lid, give it a stir and garnish with fresh coriander leaves.",
      "Serve Spicy Cabbage Rice recipe with raita of your choice.",
    ],
    nutritions: Nutritions(
      calories: 160,
      carbs: 25,
      fats: 5,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 12,
    name: "Thayir Semiya Recipe (Curd Semiya)",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Raksha_Kamat/Thayir_Curd_Semiya_recipe_Yogurt_Vermicelli_South_indian_Lunch_recipe-4.jpg",
    description: "Thayir Semiya or Curd Vermicelli is a quick dish which you can make for lunch. If you are bored of eating curd rice everyday, you can always make this Thayir semiya or curd semiya for a change. In South India, people consume curd everyday.",
    diet: Diet.veg,
    ingredients: [
      "Semiya",
      "Curd",
      "Mustard Seeds",
      "Urad Dal",
      "Curry Leaves",
      "Oil",
      "Peanuts",
      "Cashew Nuts",
    ],
    preparations: [
      "To begin making the Thayir Semiya recipe, firstly boil the vermicelli in 2 cups water. Drain it and spread on a colander.",
      "Pass cold water through it. This ensures that the vermicelli does not become sticky. Keep it aside and let it cool down.",
      "Heat a kadai/wok and add oil. Add the peanuts and roast till it turns brownish. Remove and keep it aside.",
      "In the same kadai, add more oil if needed and add the mustard seeds and after it splutters add the other ingredients meant for tempering.",
      "Add the boiled vermicelli and mix everything. Add salt to taste and mix. Finally just before serving add curd and mix well.",
      "Serve Thayir Semiya on its own for a light and healthy lunch or dinner",
    ],
    nutritions: Nutritions(
      calories: 100,
      carbs: 15,
      fats: 6,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 13,
    name: "Urulai Kizhangu Masiyal Recipe (Potatoes in a Tangy lemon and Ginger Gravy)",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/Indian_Vegetables_Gravy/Urulai_Kizhangu_Masiyal_Recipe_Potatoes_in_a_Tangy_lemon_and_Ginger_Gravy-1.jpg",
    description: "Urulai Kizhangu Masiyal Recipe (Potatoes in a Tangy lemon and Ginger Gravy) is a very classic tamil brahmin dish that is eaten along with puri's or chapatti. As a child I would not eat any potatoes apart from my favorite urulai kizhangu roast (potato roast), but now that I am all grown up and eaten things as bland as a leaf, I just love this dish. I love this dish for it tangy lemon and ginger flavors that get so well absorbed by the potatoes. The dish is made healthy using less oil, spiced just right to get the best flavors from the potatoes and the curry. Serve the Urulai Kizhangu Masiyal Recipe (Potatoes in a Tangy lemon and Ginger Gravy) along with Phulkas for a wholesome weeknight dinner.",
    diet: Diet.veg,
    ingredients: [
      "Potatoes",
      "Green Chillies",
      "Ginger",
      "Urad Dal",
      "Curry Leaves",
      "Mustard Seeds",
      "Urad Dal",
      "Turmeric Powder",
      "Oil",
      "Coriander Leaves",
      "Cashew Nuts",
    ],
    preparations: [
      "To begin making the Urulai Kizhangu Masiyal Recipe (Potatoes in a Tangy lemon and Ginger Gravy), we will first cook the potatoes until soft.",
      "Once soft, peel the potatoes and cut them into dices.",
      "The next step is to spice up the potatoes to make the Masiyal. Heat a teaspoon of oil in a heavy bottom pan on medium heat add the mustard seeds and the halved urad dal allow them to crackle and the dal to turn light golden brown.",
      "Stir in the ginger, curry leaves, turmeric powder, greenStir in the ginger, curry leaves, turmeric powder, green chillies, boiled potatoes, salt along with 1 cup of water.",
      "Turn the heat to low and simmer the Urulai Kizhangu for about 10 minutes. The mixture will look like amish mash of potatoes.",
      "Finally stir in the lemon juice and freshly chopped coriander leaves. Check the salt and spice levels and adjust to suit your taste.",
      "Serve the Urulai Kizhangu Masiyal Recipe (Potatoes in a Tangy lemon and Ginger Gravy) along with Phulkas for a wholesome weeknight dinner.",
    ],
    nutritions: Nutritions(
      calories: 100,
      carbs: 15,
      fats: 6,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 14,
    name: "Vadyancho Ross Recipe (Ash Gourd Chips Curry)",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/poojanadkarni/Vadyancho_Ross__Ash_gourd_Chips_Curry.jpg",
    description: "As a Goan, this recipe is very close to my heart. Vadyo are sun dried chips prepared out of Ash Gourd. My aunt used to prepare them, store them and use in different curries and vegetables. They just enhance the flavors of your food. In today's ross or curry, I have used them. This curry is without any onions or garlic. It is very easy to make and goes really well with rice.",
    diet: Diet.veg,
    ingredients: [
      "Ash Gourd Chips",
      "Coconut Oil",
      "Coconut",
      "Black Peppercorns",
      "Corainder Seeds",
      "Turmeric Powder",
      "Dry Red Chillies",
      "Tamarind",
    ],
    preparations: [
      "To begin making the Vadyancho Ross recipe, On a medium high heat, fry the ash gourd chips on a frying pan using a teaspoon of oil. Once they are nice and crisp on both the sides, remove them out on a plate and keep aside.",
      "Grind together grated coconut, peppercorns, coriander seeds, turmeric powder, dry red chilies and tamarind using very little water.",
      "Take the ground paste in a saucepan kept on medium heat and allow to boil. Once it boils, add the fried ash gourd chips and mix. Allow the mixture to boil for 2-3 more minutes.",
      "Finally add salt, mix and remove from heat.",
      "Serve hot. Serve Vadyancho Ross along with Steamed Rice and Suran Fodi for a weekday meal.",
    ],
    nutritions: Nutritions(
      calories: 130,
      carbs: 10,
      fats: 8,
      protiens: 4,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
  RecipeModel(
    id: 15,
    name: "Vegetable Rava Upma Recipe - Sooji Upma Recipe",
    image_url: "https://www.archanaskitchen.com/images/archanaskitchen/0-Archanas-Kitchen-Recipes/2020/Vegetable_Rava_Upma_Sooji_Upma_Recipe_Video_6_1600.jpg",
    description: "Vegetable Rava Upma is a traditional south Indian breakfast dish that is made from semolina and cooked along with vegetables and seasonings. This dish is popularly called as Khara Bath in Karnataka. At home we love to serve it along with a hot cup of freshly brewed filter coffee to make a complete breakfast with some fresh fruits on the side.",
    diet: Diet.veg,
    ingredients: [
      "Sooji",
      "Onion",
      "Ginger",
      "Curry Leaves",
      "Carrot",
      "Green Beans",
      "Mustard Seeds",
      "Urad Dal",
      "Asafoetida",
      "Oil",
      "Lemon Juice",
    ],
    preparations: [
      "To begin making the Vegetable Rava Upma Recipe/Sooji Upma, prep all the ingredients and keep aside. In a saucepan boil 3 cups of water along with salt and a dash of sugar and set aside. Add the vegetables to this water and cook it until the sooji/rava gets roasted.",
      "Heat oil in heavy bottomed pan on medium heat add mustard seeds, half urad dal seeds and allow it to crackle and the dal to turn golden brown and crisp.",
      "Stir in the onions, ginger, asafoetida, curry leaves and green chilies and saut until onions are tender.",
      "Stir in the semolina and roast along with the onion mixture until you get the light roasted aroma.",
      "Gradually pour the hot water into the above mixture and continue to stir in the process.Turn the heat to low, cover the pan and allow the Rava Upma to cook and steam in the heat.",
      "Keep stirring occasionally to avoid lumps. This will take about 10 minutes. Finally stir in the ghee and lemon juice and saut for a couple of minutes on low heat until all the ingredients are well combined.",
      "The ghee enhances the flavour of the Rava Upma/ Sooji Upma.Serve Vegetable Rava Upma Recipe along with Coconut Chutney and South Indian Filter Coffee Recipe With Filter Coffee Powder for a complete south Indian Breakfast.",
    ],
    nutritions: Nutritions(
      calories: 180,
      carbs: 30,
      fats: 6,
      protiens: 5,
      weight: 100,
    ),
    prep_time: "35min",
    cuisine: "North Indian",
  ),
];
